// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtOTsISwi3lgPxOF2X7oX85nK-Z8Ni570',
    appId: '1:419220295904:web:493388af48afe5e1054085',
    messagingSenderId: '419220295904',
    projectId: 'kamal-abu-qamar-gsg-test',
    authDomain: 'kamal-abu-qamar-gsg-test.firebaseapp.com',
    storageBucket: 'kamal-abu-qamar-gsg-test.appspot.com',
    measurementId: 'G-FRZXTYQZ62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2JD_WjMRK4f219W-kf-d65XI0wCXayNo',
    appId: '1:419220295904:android:5bb8d641492d491c054085',
    messagingSenderId: '419220295904',
    projectId: 'kamal-abu-qamar-gsg-test',
    storageBucket: 'kamal-abu-qamar-gsg-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKgvipIgyzO0vd26CkIIS8-L36E6AKJEY',
    appId: '1:419220295904:ios:46953639ee32bfab054085',
    messagingSenderId: '419220295904',
    projectId: 'kamal-abu-qamar-gsg-test',
    storageBucket: 'kamal-abu-qamar-gsg-test.appspot.com',
    iosClientId: '419220295904-sm3ve17fq9277vm5bn1jgoq1fgrocbb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.firbaseTest3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKgvipIgyzO0vd26CkIIS8-L36E6AKJEY',
    appId: '1:419220295904:ios:46953639ee32bfab054085',
    messagingSenderId: '419220295904',
    projectId: 'kamal-abu-qamar-gsg-test',
    storageBucket: 'kamal-abu-qamar-gsg-test.appspot.com',
    iosClientId: '419220295904-sm3ve17fq9277vm5bn1jgoq1fgrocbb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.firbaseTest3',
  );
}
